### ISSUE TITLE
Onderzoeken of het mogelijk is om oude builds niet te vervangen als er geen bestanden zijn aangepast

### ISSUE THREAD

**Issue by gnoesiboe** [freshheads/webpack-config-builder#70]
De hash die gebruikt wordt voor browser cache busting dus bijvoorbeeld baseren op de huidige status. Als hij hetzelfde is, hoeft de browser, na een deployment waarin niets aan de frontend is aangepast, dus ook niets opnieuw binnen te halen..

**Comment by martinbroos** [comment]
Ik was in de veronderstelling dat dit wel zo werkte, daarom hebben we ook de long term caching ingesteld.
Volgens dit artikel zou het door gebruik van chunkhash voor JS en contenthash voor css wel zo moeten werken:

https://medium.com/@sahilkkrazy/hash-vs-chunkhash-vs-contenthash-e94d38a32208

**Comment by martinbroos** [comment]
Zo te zien gaat het dan in de outputAdapter mis waar we [hash] gebruiken.

https://github.com/freshheads/webpack-config-builder/blob/master/lib/adapter/freshheads/OutputAdapter.ts#L34

**Comment by gnoesiboe** [comment]
ah, ok ;)

**Comment by martinbroos** [comment]
In de webpack docs geven ze aan[contenthash] te gebruiken dus laten we dat maar implementeren.

https://webpack.js.org/guides/caching/
