### ISSUE TITLE
ClassName optimalization when using Css Modules

### ISSUE THREAD

**Issue by RogierZeebregts** [freshheads/webpack-config-builder#75]
When using CSS Modules, classNames have to be optimized. Otherwise classNames will be Base64 hashes, which make code inspections difficult. 
Please add the following to the css options of the DefaultStackAdapter:

`cssLoaderOptions: {
    modules: {
        localIdentName: isProduction ? '[hash:base64]' : '[name]__[local]___[hash:base64:5]',
    },
},`

This way, classNames will be hashes only in production, and easy to identify in development

**Comment by martinbroos** [comment]
Beter om de hash in development weg te laten. Dus dit er van maken:

```
cssLoaderOptions: { 
          modules: { 
                  localIdentName: isProduction ? '[hash:base64]' : '[path][name]__[local], 
          }, 
},
```

Dit word ook geadviseerd in de documentatie : https://webpack.js.org/loaders/css-loader/#localidentname

**Comment by martinbroos** [comment]
Dit blijkt toch wat lastiger te zijn, wanneer je deze config toepast dan worden ook css classnames veranderd die geen css-module zijn. Hierdoor zal je styling op basis van globale classnames kapot gaan.

Wat ik zo snel zie is dat bv create react app een aparte webpack rule heeft voor .module.css files en voor al het andere. Binnen die use rule word dan de localIndentName aangepast.

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L526

**Comment by martinbroos** [comment]
Heb een opzet gemaakt hiervoor binnen een project. Door de getLocalIntent functie te overschrijven hoeven we geen aparte rules te maken voor .module files. Dit zou namelijk het toevoegen van custom configs lastiger maken in webpack config builder. 

Wat nog open staat:

* Wil je op productie wel volledig gehashte classNames? Dat werkt nu nog niet.
* Hoe gaan we dit aanbieden, altijd aan of de functie exposen in de library zodat je hem aan je config kan toevoegen als je het wil gebruiken.

https://github.com/freshheads/ofed-academy/pull/310

**Comment by gnoesiboe** [comment]
https://github.com/freshheads/webpack-config-builder/pull/100

**Comment by martinbroos** [comment]
Fixed in v3.2.0
