### ISSUE TITLE
Enable css modules camelcase

### ISSUE THREAD

**Issue by martinbroos** [freshheads/webpack-config-builder#85]
zodat we in de css wel BEM kunnen blijven gebruiken maar in JS wel valid objecten hebben.

```
.block__element
.block--modifier
```

word:
```
styles.blockElement
styles.blockModifier
```

Zie https://webpack.js.org/loaders/css-loader/#exportlocalsconvention voor implementatie

**Comment by martinbroos** [comment]
Met @gnoesiboe en @yannickfh besproken dat we toch willen vast houden aan camelCase en hiermee BEM syntax willen los laten. Maar de gedachtegang willen we wel overeind proberen te houden. Daarom is dit het voorstel:

Item.module.scss
```
.container {
  // wrapper code, could also be called .item
  
  &.isPrimary {
      // modifiers 
   }
}

.isPrimary {
    // modifier of scope - same as nested modifier example
}

.title {
  // child

   &.isLarge {
     // modfier of title
   }
}

.content {
  // child
}
```

@aida-ros @rbastiaansen @RogierZeebregts  zijn jullie het hier ook mee eens?
Modifiers willen we dus prefixen met **is** en omdat css modules al gescoped zijn hoef je niet steeds de module naam te herhalen waardoor al het andere altijd een child is van de module. Hiermee zijn de __ underscores ook overbodig.

Het voordeel is dat autocompletion beter werkt, al lijkt het ook met dashes wel goed te gaan in php storm. En er dus geen magie is die -- omzet naar camelcase. Ook wanneer je binnen een css file zou gaan extenden kun je overal dezelfde naamgeving gebruiken.

**Comment by rbastiaansen** [comment]
Jahoor, 

> Met @gnoesiboe en @yannickfh besproken dat we toch willen vast houden aan camelCase en hiermee BEM syntax willen los laten. Maar de gedachtegang willen we wel overeind proberen te houden. Daarom is dit het voorstel:
> 
> Item.module.scss
> 
> ```
> .container {
>   // wrapper code, could also be called .item
>   
>   &.isPrimary {
>       // modifiers 
>    }
> }
> 
> .isPrimary {
>     // modifier of scope - same as nested modifier example
> }
> 
> .title {
>   // child
> 
>    &.isLarge {
>      // modfier of title
>    }
> }
> 
> .content {
>   // child
> }
> ```
> 
> @aida-ros @rbastiaansen @RogierZeebregts zijn jullie het hier ook mee eens?
> Modifiers willen we dus prefixen met **is** en omdat css modules al gescoped zijn hoef je niet steeds de module naam te herhalen waardoor al het andere altijd een child is van de module. Hiermee zijn de __ underscores ook overbodig.
> 
> Het voordeel is dat autocompletion beter werkt, al lijkt het ook met dashes wel goed te gaan in php storm. En er dus geen magie is die -- omzet naar camelcase. Ook wanneer je binnen een css file zou gaan extenden kun je overal dezelfde naamgeving gebruiken.

Jahoor, dat lijkt me helemaal prima!

**Comment by aida-ros** [comment]
Ja, helder! Lijkt me goed :)

**Comment by martinbroos** [comment]
@rensio @doender kunnen jullie ook in het bovenstaande vinden, of nog opmerkingen / aanvullingen ?

**Comment by rensio** [comment]
Alles wat minder verbose is kan ik alleen maar toejuichen ;)

**Comment by martinbroos** [comment]
Ok duidelijk laten we dit issue dan closen. Ervaringen met de bovenstaande opzet hoor ik graag. We zouden het ook ergens kunnen vastleggen als dat helpt.
